CREATE TABLE IF NOT EXISTS "db_patients" (
	"source_id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"full_name" text,
	"patient_id" text,
	"zoho_id" text,
	"returning_patient" boolean,
	"locked" boolean,
	"dr_locked" text,
	"state" text,
	"dob" text,
	"used_cannabis_before" boolean,
	"mobile" text,
	"risk_rating" integer,
	"source_created_at" timestamp with time zone,
	"source_updated_at" timestamp with time zone,
	"synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "db_treatment_plans" (
	"source_id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"patient_id" text,
	"dr_id" text,
	"dr_name" text,
	"consultation_id" text,
	"outcome" text,
	"dr_notes" text,
	"date" date,
	"type" text,
	"mental_health_document" text,
	"dose_per_day_22" numeric(10, 3),
	"strength_concentration_22" text,
	"max_dose_22" numeric(10, 3),
	"total_quantity_22" numeric(10, 3),
	"number_of_repeat_22" integer,
	"supply_interval_22" integer,
	"dose_per_day_29" numeric(10, 3),
	"strength_concentration_29" text,
	"max_dose_29" numeric(10, 3),
	"total_quantity_29" numeric(10, 3),
	"number_of_repeat_29" integer,
	"supply_interval_29" integer,
	"source_created_at" timestamp with time zone,
	"source_updated_at" timestamp with time zone,
	"synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
