CREATE TABLE IF NOT EXISTS "db_treatment_plan_tracker" (
	"email" text PRIMARY KEY NOT NULL,
	"synced_date" text,
	"repeats" integer,
	"script_start_date" text,
	"script_expiration_date" text,
	"consulting_doctor" text,
	"supply_interval" integer,
	"repeats_remaining_22" numeric(10, 3),
	"repeats_remaining_26" numeric(10, 3),
	"repeats_remaining_29" numeric(10, 3),
	"supply_total_22" numeric(10, 3),
	"supply_total_26" numeric(10, 3),
	"supply_total_29" numeric(10, 3),
	"supply_used_total_22" numeric(10, 3),
	"supply_used_total_26" numeric(10, 3),
	"supply_used_total_29" numeric(10, 3),
	"supply_interval_total_22" numeric(10, 3),
	"supply_interval_total_26" numeric(10, 3),
	"supply_interval_total_29" numeric(10, 3),
	"supply_used_interval_22" numeric(10, 3),
	"supply_used_interval_26" numeric(10, 3),
	"supply_used_interval_29" numeric(10, 3),
	"supply_interval_start_22" text,
	"supply_interval_start_26" text,
	"supply_interval_start_29" text,
	"needs_update" boolean,
	"synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
